services:
  frontend:
    image: frontend
    container_name: frontend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
