services:
  frontend:
    image: frontend
    container_name: frontend_container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
